---
title       : Note-taking Research
subtitle    : Note-taking Habits and Learning
author      : andrew.chan at research.ittralee.ie
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : prettify      # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
---


Group C (Wed 11am - 1pm, T306)
---  


||Pen & Paper|Computer (Web App)|  
 --------|------|------|  
||Murry, Darren|Gyalus, Christian|  
||O'Brien, Ryan|O'Connor, Peter| 
||McGarvery, Dualta|McGlynn, Daryl|
||Moynihan, Padraig|Murphy, Jason|
||O'Connell, Kevin|O'Conchuir, Gregoir|
||Curran, David|O'Leary, Kieran|
||Lyons, John|Lovric, Alen|
||Kelter, Aishling|McMahon, Vincent|


--- .class #id 

Group A (Thu 2pm - 1pm, T304)
---  


||Pen & Paper|Computer (Web App)|  
 --------|------|------|  
||Carey, Dylan|Brody, Enda|  
||O'Sullivan, James|Walshe, Fiona| 
||Coleman, Shane|Casey, Michael|
||Bermingham, Thomas|Cronin, Harry|
||Fennell, Patrick|Heanue, Alan|
||Costello, Paul|Brophy, Jonchristopher|
||Krasniqi, Liranda|Hughes, Steven|
||Barry, Patrick|Azzam, Mahmoud|
||Barrett, Chris|Begley, Shane|  
||Maruszak, Karol|Lynch, John D|  

--- .class #id

Pen & Paper
----

* will collect your lectures notes for analysis. Notes will be returned to you next week.
* please put your student ID on the notes for identification

Computer (Web App)
----

* access the app at http://testnotes.cloudapp.net:3838/tabtest/
* please save your notes at the end of lecture and email a copy to me at andrew.chan@research.ittralee.ie



--- .class #id

Letter of Invitation
-----
  
Hi All,  
  
The research study is about students' note-taking habits and learning. Your participation in the research is completely voluntary and it will involve only:  
  
* Using a Cloud-based app or pen and paper to take notes  
* Submitting your lecture notes for analysis (the notes will be returned to you)
* Completing a short quiz at the end of the lecture (the quiz will not affect your course grade)
  
All information collected is confidential. Consent is implied when you submit your notes. 
      
My research supervisor is Helen Fitzgerald. Should you have any queries about the study or your participation in it, you may contact her or myself.  
  
Thank you for your help.  
  
Andrew Chan   


---
  
  
  
###### Please complete a short quiz at 
  
https://docs.google.com/forms/d/1Mj_57xFbtVOxBctKXMM7BkBrgq5b6JsQmR41A8gi_Yk/viewform
